---

substitutions:
  device_name: "SML2MQTT"

esphome:
  name: "smlreader"

esp32:
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  ap:
    ssid: "SML-Reader AP"
    password: !secret wifi_fallback_password

logger:
  level: ERROR

ota:
  password: !secret ota_password

web_server:
  port: 80

mqtt:
  id: mqttclient
  broker: !secret mqtt_broker

<<: !include sml-reader.yaml
